%% Initiate
% Here you can forget your past, just like "Men In Black"
clear all
close all
clc

parameters = struct(...
    'dt',0.05, ...
    'mass',1, ...
    'kernelSize',1, ...
    'gasConstantK',1, ...
    'viscosityConstant', 1, ...
    'restDensity', 0, ...
    'sigma', 72e-3, ...
    'nThreshold', 0.02, ...
    'gravity', [0 -9.82], ...
    'leftBound', 0, ...
    'rightBound', 100, ...
    'bottomBound', 0, ...
    'topBound', 100, ...
    'wallDamper', 0.6);

%% One Particle
particle = struct(...
    'density', 0, ...
    'position',[0 0], ...
    'velocity',[0 0], ...
    'pressure',0, ...
    'force',[0 0], ...
    'cs', 0);

%% Several Particles

for i = 1:50
    particles(i) = particle;
    
    % Give each particle random velocity and position
    particles(i).position = ...
        [rand*(parameters.rightBound-parameters.leftBound)+parameters.leftBound ...
        rand*(parameters.topBound-parameters.bottomBound)+parameters.bottomBound];
    particles(i).velocity = 3*[(2*rand-1) (2*rand-1)];
end

%% Calculate Properties
figure;
while true
    %tic;
    
    particles = calculateForces(particles, parameters);
    particles = performTimestep(particles, parameters.dt);
    particles = checkBoundaries(particles, parameters);
    clf;
    hold on
    
    drawParticles(particles);
    axis([(parameters.leftBound-1) (parameters.rightBound+1) (parameters.bottomBound-1) (parameters.topBound+1)]);
    
    %toc
    pause(0.01);
end